Name:           ros-indigo-qglv-extras
Version:        0.1.7
Release:        0%{?dist}
Summary:        ROS qglv_extras package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       libQGLViewer
Requires:       ros-indigo-ecl-build
Requires:       ros-indigo-qglv-opengl
Requires:       ros-indigo-sophus
BuildRequires:  eigen3-devel
BuildRequires:  libQGLViewer-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-ecl-build
BuildRequires:  ros-indigo-qglv-opengl
BuildRequires:  ros-indigo-sophus

%description
Methods and objects for working with or on top of the qglveiwer framework.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jun 16 2016 Daniel Stonier <stonier@yujinrobot.com> - 0.1.7-0
- Autogenerated by Bloom

* Tue Nov 03 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.6-0
- Autogenerated by Bloom

* Mon Nov 02 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.5-0
- Autogenerated by Bloom

* Mon Nov 02 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.4-0
- Autogenerated by Bloom

* Wed Oct 28 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.3-1
- Autogenerated by Bloom

* Wed Oct 28 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.3-0
- Autogenerated by Bloom

* Tue Oct 27 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.2-0
- Autogenerated by Bloom

* Tue Oct 20 2015 Daniel Stonier <stonier@yujinrobot.com> - 0.1.1-0
- Autogenerated by Bloom

